global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/<some_hook_id>'
route:
  receiver: 'slack-notifications'
receivers:
  - name: 'slack-notifications'
    slack_configs:
    - channel: '#slack-notify-playground'
      send_resolved: true