groups:
- name: Down
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 3m
    labels:
      severity: 'critical'
    annotations:
      summary: "Instance  is down"
      description: " of job  has been down for more than 3 minutes."

- name: AllInstances
  rules:
  - alert: UsingTooMuchMemory
    expr: node_memory_free_bytes > 0  # the condition that triggers alert
    for: 1m # the duration that the condition holds
    labels:
      severity: 'critical'
    annotations:
      summary: "Instance {{ $labels.instance }} is almost out of memory"
      description: "{{ $labels.instance }}  of job  has been down for more than 1 minutes."
- name: All
  rules:
  - alert: TooManyTCPSockets
    expr: node_sockstat_TCP_mem_bytes > 5000
    for: 1m
    labels:
      severity: 'critical'
    annotations:
      summary: "Instance {{ $labels.instance }} is has too many TCP sockets"
      description: "{{ $labels.instance }}  of job  has been problematic for more than 1 minutes."